### ISSUE TITLE
Avoid instantiating the curvature matrix when not needed

### ISSUE THREAD

**Issue by Thomas-Christie** [laplax-org/laplax#15]
Currently, curvature matrices are passed about implicitly as matrix-vector products for a lot of logic, but within the `create_posterior_function` code we explicitly instantiate the matrix (or an approximation thereof) [here](https://github.com/laplax-org/laplax/blob/main/laplax/curv/cov.py#L242) as part of the `CURVATURE_METHOD`. In some cases, the user may not need this explicit instantiation for performing downstream tasks, if these tasks can be performed via matrix-vector products using the curvature matrix-vector product. It would be nice to provide the flexibility to avoid explicitly instantiating the curvature matrix in such cases.

**Comment by bmucsanyi** [comment]
When the task is also possible without instantiating the matrix, it would be nice to have a flag for this (trading off performance with memory requirements).

**Comment by 2bys** [comment]
What examples do you have in mind, where you don't perform an approximation of the mv first? Or at least apply some form of transformation to the curvature mv product? Instantiating should only happen here based on the user-defined curvature-approximation (e.g. full approximation).
